name: Publish Extension

on: 
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn global add vsce
      - run: vsce package
      - run: vsce publish -p ${{secrets.VSCODE_TOKEN}}
